# Erase or comment out line to use default.
# null indicates default value is determined by requestBatch.py
---
export_settings:
  skip_spike_export: False
  skip_event_export : False
  skip_stream_export : False
  downsampled_rate: 1000

slurm_settings:
  # You probably want to change these
  mail-user: "lapishla@iu.edu" #For Slurm notifications
  mem: null #Memory (GB) reserved for each job (default: auto estimate from raw data size (GB * 3))
  time: null #Time (minutes) reserved for each job (default: auto estimate from raw data size (GB * 2))
  
  # You probably don't need to change these
  partition: "general"
  array: null #default: "1-{#rows in recordingSettings.csv}"
  account: "r00229" 
  mail-type: "ALL"

